println("\n                   SolidStateDetectors.jl")
println("           ~aaaaa~                        ~aaaaa~")
print("      .aa^               ")
printstyled("-*GitHub*-", bold = true, color = :blue)
println("               ^aa.")
print("     a              ")
printstyled("SolidStateDetectors*", bold = true, color = :blue)
print("              a        ")
printstyled("Solid\n", bold = true, color = 5)
print("    aaa               ")
printstyled("^*JuliaPhysics*^", bold = true, color = :blue)
print("               aaa      ")
printstyled("S\n", bold = true, color = 5)
print("   a    aaa.                 ")
printstyled("un", bold = true, color = :green)
print("                 .aaa    a      ")
printstyled("t\n", bold = true, color = 5)
print("  a          JuliaPhysics/SolidStateDetectors.jl         a      ")
printstyled("at\n", bold = true, color = 5)
print(" a                           ")
printstyled("un", bold = true, color = :green)
print("                           a       ")
printstyled("e\n", bold = true, color = 5)
print(" a                           ")
printstyled("un", bold = true, color = :green)
print("                           a        ")
printstyled("D\n", bold = true, color = 5)
print(" a                       ")
printstyled("SolidState", bold = true, color = :green)
print("                      ")
printstyled("lj.srotcete\n", bold = true, color = 5)
print(" a                     ")
printstyled("Detectors.jl-S", bold = true, color = :green)
print("                   ")
printstyled("S", bold = true, color = 5)
println(" a")
print(" a                   ")
printstyled("olidStateDetectors", bold = true, color = :green)
print("                  ")
printstyled("ol\n", bold = true, color = 5)
print(" a                   ")
printstyled(".jl-SolidStateDete", bold = true, color = :green)
print("                   ")
printstyled("id\n", bold = true, color = 5)
print(" a                  ")
printstyled("ctors.jl-SolidState*", bold = true, color = :green)
print("                  a ")
printstyled("S\n", bold = true, color = 5)
print(" a                   ")
printstyled("Detectors.jl-Solid", bold = true, color = :green)
print("                   a  ")
printstyled("ta\n", bold = true, color = 5)
print(" a                   ")
printstyled("StateDetectors.jl-", bold = true, color = :green)
print("            ")
printstyled(".srotceteDet\n", bold = true, color = 5)
print(" a                    ")
printstyled("SolidStateDetec*", bold = true, color = :green)
print("                  ")
printstyled("jl-\n", bold = true, color = 5)
print(" a                      ")
printstyled("*tors.jl-So-", bold = true, color = :green)
print("                      a")
printstyled("So\n", bold = true, color = 5)
print(" a                                                        a ")
printstyled("l\n", bold = true, color = 5)
print(" a           ")
printstyled(".SolidStat", bold = true, color = :red)
print("             ")
printstyled(".SolidStat", bold = true, color = 5)
print("            a ")
printstyled("id\n", bold = true, color = 5)
print(" a         ")
printstyled("eDetectors.jl-S", bold = true, color = :red)
print("        ")
printstyled("eDetectors.jl-S", bold = true, color = 5)
print("         a ")
printstyled("S\n", bold = true, color = 5)
print(" a")
printstyled("1u", bold = true, color = :red)
print("      ")
printstyled("olidStateDetector", bold = true, color = :red)
print("      ")
printstyled("olidStateDetector", bold = true, color = 5)
print("        a")
printstyled("at\n", bold = true, color = 5)
print(" a  ")
printstyled("^*SolidStateDetectors.jl", bold = true, color = :red)
print("    ")
printstyled("s.jl-SolidStateDete", bold = true, color = 5)
print("     ")
printstyled("~et\n", bold = true, color = 5)
print(" a       ")
printstyled("SolidStateDetectors", bold = true, color = :red)
print("    ")
printstyled("SolidStateDetectors.jl^^", bold = true, color = 5)
println("  a")
print(" a       ")
printstyled(".jl-SolidStateDetec", bold = true, color = :red)
print("    ")
printstyled("ctors.jl-SolidState", bold = true, color = 5)
println("       a")
print(" a       ")
printstyled("+tors.jl-SolidStat", bold = true, color = :red)
print("      ")
printstyled("Detectors.jl-Solid", bold = true, color = 5)
println("       a")
print(" a         ")
printstyled("eDetectors.jl-S", bold = true, color = :red)
print("        ")
printstyled("StateDetectors.j", bold = true, color = 5)
println("        a")
print(" a          ")
printstyled(".olidStateDe", bold = true, color = :red)
print("            ")
printstyled("l-SolidState", bold = true, color = 5)
println("          a")
println(" a~                                                      ~a")
println("   ~aa-                                              ~aa~")
println("        ^JuliaPhysics/SolidStateDetectors.jl-©-2025^\n")