model: ADLChargeDriftModel
phi110: -0.785398
material: HPGe
drift:
  velocity:
    model: Bruyneel2006
    parameters:
      e100:
        mu0: 3.8609
        beta: 0.805
        E0: 51100
        mun: -0.0171
      e111:
        mu0: 3.8536
        beta: 0.641
        E0: 53800
        mun: 0.051
      h100:
        mu0: 6.1824
        beta: 0.942
        E0: 18500
      h111:
        mu0: 6.1215
        beta: 0.662
        E0: 18200