name: Spherical Detector
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cartesian
  axes:
    x:
      from: -50
      to: 50
      boundaries: inf
    y:
      from: -50
      to: 50
      boundaries: inf
    z:
      from: -50
      to: 50
      boundaries: inf
medium: vacuum
detectors:
- semiconductor:
    material: HPGe
    temperature: 78
    impurity_density:
      name: constant
      value: -1e6
    charge_drift_model:
      include: ADLChargeDriftModel/drift_velocity_config.yaml
    geometry:
      difference:
      - sphere:
          r: 30
      - box:
          widths: [60, 60, 0.2]
          origin:
            z: 29.9
        
  contacts:
  - material: HPGe
    id: 1
    potential: 0
    geometry:
      tube:
        r: 5
        h: 0.2
        origin:
          z: 29.9
  - material: HPGe
    id: 2
    potential: 3500
    geometry:
      difference:
      - sphere:
          r: 30
      - union:
        - sphere:
            r: 28
        - box:
            widths: [60, 60, 40]
            origin:
              z: 20