name: Spherical Detector
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cartesian
  axes:
    x:
      from: -50
      to: 50
      boundaries: inf
    y:
      from: -50
      to: 50
      boundaries: inf
    z:
      from: -50
      to: 50
      boundaries: inf
medium: vacuum
detectors:
- bulk:
    material: HPGe
    temperature: 78
    impurity_density:
      name: constant
      value: -1000000
    charge_drift_model:
      include: ADLChargeDriftModel/drift_velocity_config.yaml
    geometry:
      difference:
      - sphere:
          r: 30
      - box:
          x:
            from: -30
            to: 30
          y:
            from: -30
            to: 30
          z:
            from: 29.8
            to: 30
  contacts:
  - material: HPGe
    channel: 1
    potential: 0
    geometry:
      tube:
        r: 5
        phi:
          from: 0
          to: 360
        z:
          from: 29.8
          to: 30
  - material: HPGe
    channel: 2
    potential: 3500
    geometry:
      difference:
      - sphere:
          r: 30
      - union:
        - sphere:
            r: 28
        - box:
            x:
              from: -30
              to: 30
            y:
              from: -30
              to: 30
            z:
              from: 0
              to: 35