name: "Cut Cone"
units:
  length: "mm"
  angle: "deg"
  potential: "V"
  temperature: "K"
grid:
  coordinates: "cylindrical"
  axes:
    r:
      to: 12.0
      boundaries: "inf"
    phi:
      from: 0
      to: 0
      boundaries: "periodic"
    z:
      from: -2
      to: 10
      boundaries:
        left: "inf"
        right: "inf"
medium: "vacuum"
include: "cone_detector.yaml"
      